use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let translations_dir = Path::new(&manifest_dir).join("../assets/translations/pumpkin");

    // Collect all .json translation files
    let mut files: Vec<String> = Vec::new();
    for entry in fs::read_dir(&translations_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "json") {
            files.push(path.file_name().unwrap().to_str().unwrap().to_string());
        }
    }

    // Sort for deterministic output
    files.sort();

    // Generate the Rust source file
    let dest_path = Path::new(&out_dir).join("generated_store.rs");
    let mut code = String::new();

    code.push_str("// AUTO-GENERATED by pumpkin-i18n build.rs - DO NOT EDIT\n\n");

    code.push_str("#[allow(clippy::too_many_lines)]\n");
    code.push_str(
        "pub(crate) fn load_all_translations() -> [std::collections::HashMap<String, String>; crate::Locale::COUNT] {\n",
    );
    code.push_str(
        "    let mut array: [std::collections::HashMap<String, String>; crate::Locale::COUNT] = std::array::from_fn(|_| std::collections::HashMap::new());\n\n",
    );

    // Vanilla en_us_java.json with "minecraft:" prefix
    code.push_str("    // Vanilla en_us (minecraft namespace)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let vanilla: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/vanilla/en_us_java.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse en_us_java.json\");\n");
    code.push_str("        for (key, value) in vanilla {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"minecraft:{key}\"), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Pumpkin translation files with "pumpkin:" prefix
    for file in &files {
        let stem = file.strip_suffix(".json").unwrap();
        let variant = filename_to_variant(stem);

        let _ = writeln!(code, "    // Pumpkin {stem}");
        code.push_str("    {\n");
        code.push_str(
            "        let pumpkin: std::collections::HashMap<String, String> = serde_json::from_str(\n",
        );
        let _ = writeln!(
            code,
            "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/pumpkin/{file}\"))"
        );
        let _ = writeln!(code, "        ).expect(\"Could not parse {file}\");");
        code.push_str("        for (key, value) in pumpkin {\n");
        let _ = writeln!(
            code,
            "            array[crate::Locale::{variant} as usize].insert(format!(\"pumpkin:{{key}}\"), value);"
        );
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    code.push_str("    array\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    // Rebuild tracking
    println!("cargo::rerun-if-changed=../assets/translations/pumpkin/");
    println!("cargo::rerun-if-changed=../assets/translations/vanilla/en_us_java.json");
}

/// Converts a lowercase underscore-delimited filename stem to a Locale variant name.
/// e.g. `` `af_za` `` -> `` `AfZa` ``, `bar` -> `Bar`, `` `zlm_arab` `` -> `` `ZlmArab` ``
fn filename_to_variant(stem: &str) -> String {
    stem.split('_')
        .map(|part| {
            let mut chars = part.chars();
            chars.next().map_or_else(String::new, |first| {
                first
                    .to_uppercase()
                    .chain(chars.flat_map(char::to_lowercase))
                    .collect()
            })
        })
        .collect()
}
