use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    let translations_dir = Path::new(&manifest_dir).join("../assets/translations");

    // Collect all .json translation files
    let mut files: Vec<String> = Vec::new();
    for entry in fs::read_dir(&translations_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().map_or(false, |ext| ext == "json") {
            files.push(path.file_name().unwrap().to_str().unwrap().to_string());
        }
    }

    // Sort for deterministic output
    files.sort();

    // Generate the Rust source file
    let dest_path = Path::new(&out_dir).join("generated_store.rs");
    let mut code = String::new();

    code.push_str("// AUTO-GENERATED by pumpkin-i18n build.rs - DO NOT EDIT\n\n");

    code.push_str(
        "pub(crate) fn load_all_translations() -> [std::collections::HashMap<String, String>; crate::Locale::COUNT] {\n",
    );
    code.push_str(
        "    let mut array: [std::collections::HashMap<String, String>; crate::Locale::COUNT] = std::array::from_fn(|_| std::collections::HashMap::new());\n\n",
    );

    // Vanilla en_us_java.json with "minecraft:" prefix
    code.push_str("    // Vanilla en_us (minecraft namespace)\n");
    code.push_str("    {\n");
    code.push_str(
        "        let vanilla: std::collections::HashMap<String, String> = serde_json::from_str(\n",
    );
    code.push_str(
        "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/en_us_java.json\"))\n",
    );
    code.push_str("        ).expect(\"Could not parse en_us_java.json\");\n");
    code.push_str("        for (key, value) in vanilla {\n");
    code.push_str(
        "            array[crate::Locale::EnUs as usize].insert(format!(\"minecraft:{}\", key), value);\n",
    );
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // Pumpkin translation files with "pumpkin:" prefix
    for file in &files {
        let stem = file.strip_suffix(".json").unwrap();
        let variant = filename_to_variant(stem);

        code.push_str(&format!("    // Pumpkin {}\n", stem));
        code.push_str("    {\n");
        code.push_str(
            "        let pumpkin: std::collections::HashMap<String, String> = serde_json::from_str(\n",
        );
        code.push_str(&format!(
            "            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../assets/translations/{}\"))\n",
            file
        ));
        code.push_str(&format!(
            "        ).expect(\"Could not parse {}\");\n",
            file
        ));
        code.push_str("        for (key, value) in pumpkin {\n");
        code.push_str(&format!(
            "            array[crate::Locale::{} as usize].insert(format!(\"pumpkin:{{}}\", key), value);\n",
            variant
        ));
        code.push_str("        }\n");
        code.push_str("    }\n\n");
    }

    code.push_str("    array\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();

    // Rebuild tracking
    println!("cargo::rerun-if-changed=../assets/translations/");
    println!("cargo::rerun-if-changed=../assets/en_us_java.json");
}

/// Converts a lowercase underscore-delimited filename stem to a Locale variant name.
/// e.g. "af_za" -> "AfZa", "bar" -> "Bar", "zlm_arab" -> "ZlmArab"
fn filename_to_variant(stem: &str) -> String {
    stem.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first
                    .to_uppercase()
                    .chain(chars.flat_map(|c| c.to_lowercase()))
                    .collect(),
            }
        })
        .collect()
}
