[files]
extend-exclude = ["assets/", "crates/pumpkin-data/src/generated"]

[default.extend-words]
handled = "handled"
thr = "thr"
nd = "nd"
received = "received"
ba = "ba"
fo = "fo"
undescore = "undescore"
replaceables = "replaceables"

[default.extend-identifiers]
iy = "iy"
iz = "iz"
